# Generated by Django 5.1.7 on 2025-06-29 12:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0003_alter_appointment_doctor_alter_appointment_patient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="receiver",
        ),
        migrations.RemoveField(
            model_name="message",
            name="sender",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="doctor",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="patient",
        ),
        migrations.DeleteModel(
            name="Appointment",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.DeleteModel(
            name="Prescription",
        ),
    ]
