# Generated by Django 5.2.2 on 2025-06-04 17:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateTimeField(verbose_name="Randevu Tarihi")),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("notification_sent", models.BooleanField(default=False, verbose_name="Bildirim Gönderildi")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma Tarihi")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Güncellenme Tarihi")),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_doctor_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_patient_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Randevu",
                "verbose_name_plural": "Randevular",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                (
                    "exercise_type",
                    models.CharField(
                        choices=[
                            ("walking", "Yürüyüş"),
                            ("running", "Koşu"),
                            ("cycling", "Bisiklet"),
                            ("swimming", "Yüzme"),
                            ("strength", "Kuvvet Antrenmanı"),
                            ("yoga", "Yoga"),
                            ("other", "Diğer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("duration", models.IntegerField(help_text="Süre (dakika)")),
                (
                    "intensity",
                    models.IntegerField(
                        help_text="Yoğunluk (1-10)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("calories_burned", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Egzersiz",
                "verbose_name_plural": "Egzersizler",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="HospitalRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("intervention", "Müdahale"),
                            ("xray", "Röntgen"),
                            ("blood_test", "Kan Testi"),
                            ("lab_test", "Laboratuvar Testi"),
                            ("imaging", "Görüntüleme"),
                            ("treatment", "Tedavi"),
                        ],
                        max_length=20,
                        verbose_name="Kayıt Tipi",
                    ),
                ),
                ("date", models.DateField(verbose_name="Tarih")),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                ("description", models.TextField(verbose_name="Açıklama")),
                ("results", models.TextField(verbose_name="Sonuçlar")),
                ("notes", models.TextField(blank=True, null=True, verbose_name="Notlar")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Hasta"
                    ),
                ),
            ],
            options={
                "verbose_name": "Hastane Kaydı",
                "verbose_name_plural": "Hastane Kayıtları",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BloodTestResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("parameter", models.CharField(max_length=100, verbose_name="Parametre")),
                ("value", models.CharField(max_length=50, verbose_name="Değer")),
                ("unit", models.CharField(max_length=20, verbose_name="Birim")),
                ("reference_range", models.CharField(max_length=100, verbose_name="Referans Aralığı")),
                ("is_abnormal", models.BooleanField(default=False, verbose_name="Anormal mi?")),
                (
                    "hospital_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blood_test_results",
                        to="health_data.hospitalrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kan Testi Sonucu",
                "verbose_name_plural": "Kan Testi Sonuçları",
            },
        ),
        migrations.CreateModel(
            name="LabTestResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("test_name", models.CharField(max_length=200, verbose_name="Test Adı")),
                ("result", models.TextField(verbose_name="Sonuç")),
                ("interpretation", models.TextField(verbose_name="Yorum")),
                (
                    "hospital_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_test_results",
                        to="health_data.hospitalrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Laboratuvar Testi Sonucu",
                "verbose_name_plural": "Laboratuvar Testi Sonuçları",
            },
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="İlaç adı", max_length=100)),
                ("dosage", models.CharField(help_text="Doz", max_length=50)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Günde Bir"),
                            ("twice_daily", "Günde İki"),
                            ("three_times_daily", "Günde Üç"),
                            ("four_times_daily", "Günde Dört"),
                            ("weekly", "Haftada Bir"),
                            ("custom", "Özel"),
                        ],
                        help_text="Kullanım sıklığı",
                        max_length=20,
                    ),
                ),
                (
                    "custom_frequency",
                    models.CharField(
                        blank=True, help_text="Özel kullanım sıklığı (örn: Her 8 saatte bir)", max_length=100
                    ),
                ),
                ("start_date", models.DateField(help_text="Başlangıç tarihi")),
                ("end_date", models.DateField(blank=True, help_text="Bitiş tarihi", null=True)),
                ("notes", models.TextField(blank=True)),
                ("reminder_times", models.JSONField(default=list, help_text="Hatırlatma saatleri (HH:MM formatında)")),
                ("is_active", models.BooleanField(default=True)),
                ("last_reminder_sent", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "İlaç",
                "verbose_name_plural": "İlaçlar",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(max_length=200, verbose_name="Konu")),
                ("content", models.TextField(verbose_name="Mesaj")),
                (
                    "message_type",
                    models.CharField(
                        choices=[("chat", "Sohbet"), ("reminder", "Hatırlatma")],
                        default="chat",
                        max_length=20,
                        verbose_name="Mesaj Tipi",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Gönderilme Tarihi")),
                ("is_read", models.BooleanField(default=False, verbose_name="Okundu")),
                (
                    "parent_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="health_replies",
                        to="health_data.message",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_received_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_medication",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reminder_messages",
                        to="health_data.medication",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mesaj",
                "verbose_name_plural": "Mesajlar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Sleep",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("sleep_time", models.TimeField(help_text="Uyku başlangıç saati")),
                ("wake_time", models.TimeField(help_text="Uyanma saati")),
                (
                    "quality",
                    models.IntegerField(
                        choices=[(1, "Çok Kötü"), (2, "Kötü"), (3, "Orta"), (4, "İyi"), (5, "Çok İyi")]
                    ),
                ),
                ("duration", models.DecimalField(decimal_places=1, help_text="Uyku süresi (saat)", max_digits=4)),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sleep_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Uyku Kaydı",
                "verbose_name_plural": "Uyku Kayıtları",
                "ordering": ["-date"],
            },
        ),
    ]
