# Generated by Django 5.1.7 on 2025-03-26 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "exercise_type",
                    models.CharField(
                        choices=[
                            ("walking", "Yürüyüş"),
                            ("running", "Koşu"),
                            ("cycling", "Bisiklet"),
                            ("swimming", "Yüzme"),
                            ("strength", "Kuvvet Antrenmanı"),
                            ("yoga", "Yoga"),
                            ("other", "Diğer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("duration", models.IntegerField(help_text="Süre (dakika)")),
                (
                    "intensity",
                    models.IntegerField(
                        help_text="Yoğunluk (1-10)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("calories_burned", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Egzersiz",
                "verbose_name_plural": "Egzersizler",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="İlaç adı", max_length=100)),
                ("dosage", models.CharField(help_text="Doz", max_length=50)),
                (
                    "frequency",
                    models.CharField(help_text="Kullanım sıklığı", max_length=100),
                ),
                ("start_date", models.DateField(help_text="Başlangıç tarihi")),
                (
                    "end_date",
                    models.DateField(blank=True, help_text="Bitiş tarihi", null=True),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "reminder_time",
                    models.TimeField(blank=True, help_text="Hatırlatma saati", null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "İlaç",
                "verbose_name_plural": "İlaçlar",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Sleep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("sleep_time", models.TimeField(help_text="Uyku başlangıç saati")),
                ("wake_time", models.TimeField(help_text="Uyanma saati")),
                (
                    "quality",
                    models.IntegerField(
                        choices=[
                            (1, "Çok Kötü"),
                            (2, "Kötü"),
                            (3, "Orta"),
                            (4, "İyi"),
                            (5, "Çok İyi"),
                        ]
                    ),
                ),
                (
                    "duration",
                    models.DecimalField(decimal_places=1, help_text="Uyku süresi (saat)", max_digits=4),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Uyku Kaydı",
                "verbose_name_plural": "Uyku Kayıtları",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="VitalSigns",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "blood_pressure_systolic",
                    models.IntegerField(
                        blank=True,
                        help_text="Sistolik kan basıncı (mmHg)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(70),
                            django.core.validators.MaxValueValidator(200),
                        ],
                    ),
                ),
                (
                    "blood_pressure_diastolic",
                    models.IntegerField(
                        blank=True,
                        help_text="Diastolik kan basıncı (mmHg)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(40),
                            django.core.validators.MaxValueValidator(130),
                        ],
                    ),
                ),
                (
                    "heart_rate",
                    models.IntegerField(
                        blank=True,
                        help_text="Nabız (bpm)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(40),
                            django.core.validators.MaxValueValidator(200),
                        ],
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Vücut sıcaklığı (°C)",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(35),
                            django.core.validators.MaxValueValidator(42),
                        ],
                    ),
                ),
                (
                    "blood_sugar",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Kan şekeri (mmol/L)",
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(2),
                            django.core.validators.MaxValueValidator(30),
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Vital Bulgu",
                "verbose_name_plural": "Vital Bulgular",
                "ordering": ["-date"],
            },
        ),
    ]
