# Generated by Django 5.1.7 on 2025-05-21 16:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("health_data", "0004_appointment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medication",
            name="reminder_time",
        ),
        migrations.AddField(
            model_name="medication",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="medication",
            name="custom_frequency",
            field=models.CharField(
                blank=True, help_text="Özel kullanım sıklığı (örn: Her 8 saatte bir)", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="medication",
            name="last_reminder_sent",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medication",
            name="reminder_times",
            field=models.JSONField(default=list, help_text="Hatırlatma saatleri (HH:MM formatında)"),
        ),
        migrations.AddField(
            model_name="medication",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="medication",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("daily", "Günde Bir"),
                    ("twice_daily", "Günde İki"),
                    ("three_times_daily", "Günde Üç"),
                    ("four_times_daily", "Günde Dört"),
                    ("weekly", "Haftada Bir"),
                    ("custom", "Özel"),
                ],
                help_text="Kullanım sıklığı",
                max_length=20,
            ),
        ),
    ]
