# Generated by Django 5.1.7 on 2025-05-21 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("health_data", "0005_remove_medication_reminder_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[("chat", "Sohbet"), ("reminder", "Hatırlatma")],
                default="chat",
                max_length=20,
                verbose_name="Mesaj Tipi",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="related_medication",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reminder_messages",
                to="health_data.medication",
            ),
        ),
    ]
